# Generated by Django 5.1.2 on 2025-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar', models.CharField(default='🐍', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('unlocked_step', models.IntegerField(default=1)),
            ],
        ),
    ]
