# Generated by Django 5.1.2 on 2025-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_satisfactionsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='completion_time_seconds',
            field=models.IntegerField(blank=True, help_text='Tempo total para concluir o curso em segundos', null=True),
        ),
    ]
