# Generated by Django 5.1.2 on 2025-10-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_completion_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='research_notes',
            field=models.TextField(blank=True, help_text='Anotações da pesquisa da Etapa 5', null=True),
        ),
    ]
